
services:

  item-db:

    image: mongo:3

    volumes:

      - app-db:/data/db

    environment:

      DB_ROOT_PASSWORD: dicoding

      DB_DATABASE: todo-db


  item-app:

    image: item-app

    command: sh -c "yarn install && yarn run dev"

    ports:

      - 80:80

    working_dir: /app

    volumes:

      - ./:/app

    environment:

      DB_HOST: mysql

      DB_USER: root

      DB_PASSWORD: dicoding

      MONGO_DB: todo-db


volumes:

  app-db: